- name: create slim project
  shell: composer create-project --no-interaction --stability=dev akrabat/slim3-skeleton /var/www/slim-app

- name: run composer update
  shell: chdir="/var/www/slim-app/" composer update --prefer-dist -o
